### ISSUE TITLE
خطا

### ISSUE THREAD

**Issue by GithubUN89** [ImanMontajabi/TLS-Checker#10]
سلام
من کد زیر رو زدم 
pip install -r requirements.txt

اما خطای زیر رو میده
مشکل چیه ؟

PS C:\TLS-Checker-1.2.1\TLS-Checker-1.2.1> pip install -r requirements.txt
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ImanMontajabi** [comment]
> سلام من کد زیر رو زدم pip install -r requirements.txt
> 
> اما خطای زیر رو میده مشکل چیه ؟
> 
> PS C:\TLS-Checker-1.2.1\TLS-Checker-1.2.1> pip install -r requirements.txt pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> 
> * pip install -r requirements.txt
> * ```
>     + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

این آموزش هارو دنبال کن:
https://camelcase.ir/pip-in-cmd/
و همینطور:
https://sabzdanesh.com/set-python-path/
