### ISSUE TITLE
اضافه کردن لیست شخصی

### ISSUE THREAD

**Issue by cy33r** [ImanMontajabi/TLS-Checker#12]
**سلام اگر بخوایم لیست شخصی خودمون رو اسکن کنه از مثلا 100 سایت خودمون  چطور باید اضافه کنیم ممنون میشم راهنمایی کنید

باتشکر**

**Comment by ImanMontajabi** [comment]
> **سلام اگر بخوایم لیست شخصی خودمون رو اسکن کنه از مثلا 100 سایت خودمون چطور باید اضافه کنیم ممنون میشم راهنمایی کنید
> 
> باتشکر**

سلام یکی از فایل ها مثلا irani.csv رو با فایل خودت جایگزین کن دقت کن که آدرسا همه‌ی توی یک ستون بدون چیز اضافه‌ای باشند، یک بار با اکسل irani.csv رو بازکن درست شبیه همون یک فایل دلخواه بساز و جایگزین کن

**Comment by cy33r** [comment]
**ممنونم دارم انجام میدم حقیقتا گفتم شاید جواب نده برای همین قبلش پرسیدم 
ممنونم**
