### ISSUE TITLE
[BUG] It shows nothing.

### ISSUE THREAD

**Issue by rafiee** [ImanMontajabi/TLS-Checker#13]
با سلام
به من ارور زیر رو نشون میده. البته اروری نیست ولی هیچ سایتی نشون نمیده !
`- Which file? [i=irani.csv or 1=file1.csv or 2=file2.csv]:i                                                             + irani.csv is selected.                                                                                                - How many url of "irani.csv" do you want to check? [1-12861]:5                                                         + 5 urls are selected.                                                                                                  - Do you want to use randomized search? [y=YES, n=NO]:y                                                                 + Randomized search is selected.                                                                                        * Guide: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes                                                   - preferred country? [DE=Germany, NL=Netherland,...]:DE                                                                 - preferred AS Organization? [Hetzner, Vultr, OVH, Akamai,...]:                                                         ••••••••••••••••••••••••••••••••••••• ◒←[?25h←[?25h←[?25h←[?25h←[?25h `

**Comment by ImanMontajabi** [comment]
> با سلام به من ارور زیر رو نشون میده. البته اروری نیست ولی هیچ سایتی نشون نمیده ! `- Which file? [i=irani.csv or 1=file1.csv or 2=file2.csv]:i + irani.csv is selected. - How many url of "irani.csv" do you want to check? [1-12861]:5 + 5 urls are selected. - Do you want to use randomized search? [y=YES, n=NO]:y + Randomized search is selected. * Guide: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes - preferred country? [DE=Germany, NL=Netherland,...]:DE - preferred AS Organization? [Hetzner, Vultr, OVH, Akamai,...]: ••••••••••••••••••••••••••••••••••••• ◒←[?25h←[?25h←[?25h←[?25h←[?25h `

سلام مشکل اون 25h 25h که نشون میده برای استفاده از CMD هست از نسخه‌ی جدید power shell و terminal ویندوز که لینکش توی صفحه‌ی توضیحات هست استفاده کن و اون عدد که وارد میکنی تعداد خروجی ها نیست بلکه تعداد آدرس‌هاییه که بررسی میخواد بشه، دامنه‌ی سرچ رو وسیع تر کن تا به جواب برسی مثلا 50 تا یا 500 تا و...
