### ISSUE TITLE
مشکل در ورژن 1.2.3

### ISSUE THREAD

**Issue by AliINL** [ImanMontajabi/TLS-Checker#15]
در ورژن 1.2.3 به من هیچ خروجی نمیده
روی همون سیستم و همون اینترنت و همون ورژن poweshell و terminal ورژن 1.2.2 به درستی کار می‌کنه، اما ورژن 1.2.3 نه
با آخرین نسخه poweshell و terminal هم نسخه 1.2.3 رو تست کردم، اما خروجی هیچی نمیده. (روی ۳ تا سیستم، ۳ تا اینترنت متفاوت ورژن 1.2.3 رو تست کردم اما بازم کار نمی‌کنه)
توی کنسول هیچ result ای نمیده، فایل result.json هم خالیه

**Comment by ImanMontajabi** [comment]
بعض وقتا که سایتی که ازش api رایگان گرفتم اورلود میشه بعد چندساعت دوباره درست میشه به خاطر اونه. الان تست کردم موردی نداشت، ضمنا حین اجرا قطعش کنی چیزی ذخیره نمیشه باید تا آخر بره 🤝

**Comment by ImanMontajabi** [comment]
> در ورژن 1.2.3 به من هیچ خروجی نمیده روی همون سیستم و همون اینترنت و همون ورژن poweshell و terminal ورژن 1.2.2 به درستی کار می‌کنه، اما ورژن 1.2.3 نه با آخرین نسخه poweshell و terminal هم نسخه 1.2.3 رو تست کردم، اما خروجی هیچی نمیده. (روی ۳ تا سیستم، ۳ تا اینترنت متفاوت ورژن 1.2.3 رو تست کردم اما بازم کار نمی‌کنه) توی کنسول هیچ result ای نمیده، فایل result.json هم خالیه

بعض وقتا سایتی که ازش api رایگان گرفتم اورلود میشه بعد چندساعت دوباره درست میشه به خاطر اونه. الان تست کردم موردی نداشت، ضمنا حین اجرا قطعش کنی چیزی ذخیره نمیشه باید تا آخر بره
تغییرات دو نسخه‌ی آخر فقط توی نصب اولیه‌ی پکیج هاست بقیه‌ی کد فرقی ندارن
