### ISSUE TITLE
تست پینگ و سرعت

### ISSUE THREAD

**Issue by mahsamcse** [ImanMontajabi/TLS-Checker#16]
سلام
میشه در نتایج، تست پینگ و سرعت هم درج بشه نسبت به اون دیتا سنتری که انتخاب کردیم ؟
اینطوری میشه انتخاب های بهینه تری داشت
ممنون

**Comment by ImanMontajabi** [comment]
سلام بله حتما اینکارو انجام میدم فقط تا چند ماه آینده ☹️ الان واقعا سرم شلوغه

**Comment by ImanMontajabi** [comment]
> سلام میشه در نتایج، تست پینگ و سرعت هم درج بشه نسبت به اون دیتا سنتری که انتخاب کردیم ؟ اینطوری میشه انتخاب های بهینه تری داشت ممنون

سلام بله حتما اینکارو انجام میدم فقط تا چند ماه آینده ☹️ الان واقعا سرم شلوغه

**Comment by mahsamcse** [comment]
ممنون از شما
پس فعلا تا اون موقع اگه سایتی میشناسین که این کارو میتونه انجام بده (ینی دامنرو بهش بدیم تست پینگ و سرعت بگیره با دیتاسنتر مورد نظر) ممنون میشم در صفحه اصلی اسکریپ معرفی کنید

**Comment by ImanMontajabi** [comment]
> ممنون از شما پس فعلا تا اون موقع اگه سایتی می شناسین که این کارو میتونه انجام بده (ینی دامنرو بهش بدیم تست پینگ و سرعت بگیره با دیتاسنتر مورد نظر) ممنون میشم در صفحه اصلی اسکریپ معرفی کنید

تست واقعی بخوای انجام بدی باید sni کانفیگ سرور و کلاینت یکی باشه (مثل قضیه‌ی آی‌پی تمیز کلادفلر نیست) برای پیدا کردن وایت لیست و یا نقطه ضعف فایروال باید کلی تست انجام بشه فعلا فقط با آزمون و خطا میشه به نتیجه رسید.
