### ISSUE TITLE
عدم دانلود علی رغم پینگ خوب

### ISSUE THREAD

**Issue by itsmostafa75** [ImanMontajabi/TLS-Checker#18]
اقا ایمان مرسی از زحمتی که کشیدی
برای ایرانسل وadsl پاسخگو هستش
اما روی همراه اول چندین روز تست کردم،دامین هایی که میده وقتی میزارم توی sni،کانفیگ پنیگ عالی میده اما هیچ دیتایی رو نمیتونه عبور بده و هیچی دانلود نمیشه
همزمان همون کانفیگ روی ایرانسل سرعت دانلودش خیلی خوبه،منظورم اینه کانفیگ سالمه ولی کلا روی همراه اول کار نمیکنه 
چیکار باید بکنیم؟اینا چه روشی پیاده کردن که این اتفاق افتاده؟الان فقط دامنه اسپید تست روی همراه اول کار می‌کنه.چند تا سرور مختلف با ایپی تمیزم چک کردم ولی غیر از اسپیدتست،دامین دیگه ای روی همراه اول کار نمیکنه.میشه پیگیری کنین ببینین از چه روشی میشه نتیجه اسکریپت رو برای همراه اول بهینه تر کرد؟مرسی از کمکهای شما

**Comment by ImanMontajabi** [comment]
> اقا ایمان مرسی از زحمتی که کشیدی برای ایرانسل وadsl پاسخگو هستش اما روی همراه اول چندین روز تست کردم،دامین هایی که میده وقتی میزارم توی sni،کانفیگ پنیگ عالی میده اما هیچ دیتایی رو نمیتونه عبور بده و هیچی دانلود نمیشه همزمان همون کانفیگ روی ایرانسل سرعت دانلودش خیلی خوبه،منظورم اینه کانفیگ سالمه ولی کلا روی همراه اول کار نمیکنه چیکار باید بکنیم؟اینا چه روشی پیاده کردن که این اتفاق افتاده؟الان فقط دامنه اسپید تست روی همراه اول کار می‌کنه.چند تا سرور مختلف با ایپی تمیزم چک کردم ولی غیر از اسپیدتست،دامین دیگه ای روی همراه اول کار نمیکنه.میشه پیگیری کنین ببینین از چه روشی میشه نتیجه اسکریپت رو برای همراه اول بهینه تر کرد؟مرسی از کمکهای شما

سلام خیلی ممنون لطف داری.  برای همراه اول از هیستریا هم میشه استفاده کرد یا همون سرور های اسپیدتست، لینکش اینه: https://gist.github.com/ofou/654efe67e173a6bff5c64ba26c09d058
فکرکنم وایت لیست و گری‌لیست و بلک لیست درست کردن، اسپیدتست داخل وایت لیسته و دامنه‌هارو با آی‌پی سروراشون مپ کردند. کلی پروتکل دیگه هست اونا رو رو همراه اول تست کنید همه رو باهم همزمان نمیبندن

**Comment by itsmostafa75** [comment]
ممنونم 🙏🙏🙏
