### ISSUE TITLE
نیاوردن اس ان ای ها 

### ISSUE THREAD

**Issue by Prodenamir** [ImanMontajabi/TLS-Checker#19]
درود ، بنده تمام مراحل و کد هارو زدم و گزینه هارو هم انخاب کردم.
ولی در مرحله ای که باید سرچینگ بزنه دوتا  مینویسه 25h?] و بعد چند دقیقه دوباره میاد تو دستور tls_checker 1.7 ، کلا اس ان ای هارو سرچ و نمیاره.
![IMG_20230808_230814_164](https://github.com/ImanMontajabi/TLS-Checker/assets/141224174/94226a0d-581f-4ef1-a92a-56d15baef608)

**Comment by ImanMontajabi** [comment]
> درود ، بنده تمام مراحل و کد هارو زدم و گزینه هارو هم انخاب کردم. ولی در مرحله ای که باید سرچینگ بزنه دوتا مینویسه 25h?] و بعد چند دقیقه دوباره میاد تو دستور tls_checker 1.7 ، کلا اس ان ای هارو سرچ و نمیاره. ![IMG_20230808_230814_164](https://user-images.githubusercontent.com/141224174/259211625-94226a0d-581f-4ef1-a92a-56d15baef608.jpg)

سلام برای اون ارور از terminal و powershell7 استفاده کنید توی صفحه توضیحات گذاشتم. توی اون کانفیگی که انجام دادید سرور مدنظرتون رو پیدا نکرده با حالت‌های دیگه تست کنید
