### ISSUE TITLE
پیدا کردن تعداد کم نتایج

### ISSUE THREAD

**Issue by imaniy1994** [ImanMontajabi/TLS-Checker#2]
عرض ادب مشکلی که داشتم این بود که با هر روشی جلو میرفتم تعداد مشخصی سایت به من نشون داده میشد مثالا میگفتم 200 تا رو اسکن کن در نتیجه 2 تا سایت به من نشون میداد این یعنی 198 تا ناموفق بودن در اسکن ها؟ فایل ایرانی که برای من عموما چیزی نمایش داده نمیشد اصلا.

**Comment by ImanMontajabi** [comment]
سلام یک بار تمام سوالای اول برنامه رو فقط اینتر بزن و چیزی وارد نکن و نتیجشو به من بگو لطفا

**Comment by ImanMontajabi** [comment]
وقتی سوال سوم یعنی کشور رو تعیین کنی تعداد جواب ها کم میشن

**Comment by ImanMontajabi** [comment]
موردی بود بگو بهم مرسی

**Comment by iaghapour** [comment]
> موردی بود بگو بهم مرسی

ایمان جان نحوه عملکرد رو توضیح میدادی خوب بود.
مثالا وقتی اسکن میزنی و کشور رو de میزنی چقدر باید صبر کنی تا نتایج مشخص بشه و اصلا بفهمی این اسکریپت دار کار میکنه یا نه؟
مثالا من 3 کشور رو تست کردم و یکی 2 دقیقه صبر کردم دیدم چیزی نیاورد کلا بستم اسکنر رو چون هیچ چیزی جز صفحه سیاه وجود نداشت و انگار هیچ نتیجه ای نتونست برگردونه/

اگه بتونی منطقه بندی هم بکنی خوب میشه مثالا بگی قاره اسیا رو بگرده یا افریقا و... 
البته شاید پیشنهاد خوبی نیست نمیدونم.
در هر صورت خسته نباشید.
