### ISSUE TITLE
عدم جستجو با نت همراه اول و ایرانسل

### ISSUE THREAD

**Issue by ebiraaam** [ImanMontajabi/TLS-Checker#20]
سلام با نت همراه اول و ایرانسل اصلا جستجو نمیکنه همش استپ هست.ولی با نت adsl مخابرات جستجو میکنه چرا؟؟ روی ویندوز 10

**Comment by ImanMontajabi** [comment]
> سلام با نت همراه اول و ایرانسل اصلا جستجو نمیکنه همش استپ هست.ولی با نت adsl مخابرات جستجو میکنه چرا؟؟ روی ویندوز 10

عجیبه واقعا :)  نوع نت فرقی نداره تو جواب هرکدوم جواب میده همونو بزنید

**Comment by ebiraaam** [comment]
الان با فیلترشکن جستجو زدم شد و وسط جستجو فیلترشکن رو خاموش کردم داره جستجو میکنه الان خخخخ

**Comment by ImanMontajabi** [comment]
> الان با فیلترشکن جستجو زدم شد و وسط جستجو فیلترشکن رو خاموش کردم داره جستجو میکنه الان خخخخ

:))))

**Comment by ebiraaam** [comment]
داش اینو جدید پیدا کردم ببین
https://github.com/yonggekkk/warp-yg

گفته اتومات اکانت وایرگارد+وارپ درست میکنه میده.اینو ب ایمان بده بررسی کنه یکی از بچه ها تستش کرده

**Comment by ImanMontajabi** [comment]
> داش اینو جدید پیدا کردم ببین https://github.com/yonggekkk/warp-yg
> 
> گفته اتومات اکانت وایرگارد+وارپ درست میکنه میده.اینو ب ایمان بده بررسی کنه یکی از بچه ها تستش کرده

بی دردسر با اپ نکوباکس میشه  وایرگارد+وارپ درست کرد و خود اپ 1.1.1.1 warp هم عالی کار میکنه این اسکریپته سرور میخواد وایرگارد رو اکثر اپراتورا مسدود شده

**Comment by ebiraaam** [comment]
داش همراه اول رسما بگام داده خخخخ همش فیلتر میکنه بی ناموس..از دیروز صبح تا الان نخوابیدم پیگیر سرورام الان اگه چهرمو ببینی شدم شبی زامبی خخخخ..داش از چ روشی مطمین تره برای همراه اول ؟؟

**Comment by ImanMontajabi** [comment]
> داش همراه اول رسما بگام داده خخخخ همش فیلتر میکنه بی ناموس..از دیروز صبح تا الان نخوابیدم پیگیر سرورام الان اگه چهرمو ببینی شدم شبی زامبی خخخخ..داش از چ روشی مطمین تره برای همراه اول ؟؟

سلام همینایی که اسکریپت پیدا میکنه و speedtest اگه جواب نمیده پروتکلای دیگه رو امتحان کن همزمان همشون بسته نمیشن یکیو ببندن یکی دیگه دوباره کار میکنه من اینکارو میکنم. کلا آی‌پی سرورتو public key و short id کانفیگو مرتب عوض کنی بهتره

**Comment by ebiraaam** [comment]
داش من سرور ایران دارم برای تانل.چ روشی پیشنهاد میدی برای تانل؟؟
و اینم بگو گروه داری توی تلگرام ؟اگه داری لینکشو بفرست مرسی

**Comment by ImanMontajabi** [comment]
> داش من سرور ایران دارم برای تانل.چ روشی پیشنهاد میدی برای تانل؟؟ و اینم بگو گروه داری توی تلگرام ؟اگه داری لینکشو بفرست مرسی

نه والا گروه ندارم. 
این روشا خوبن:
https://youtu.be/Currb11YeFU?si=OQIigcgzDp347g7D
====================
https://youtu.be/dmLRXUX_PAQ?si=fByP4CQCPDbNx1Sv
====================
https://youtu.be/rFXG6SdcqWw?si=elMy__q6ItaFIKne

**Comment by ebiraaam** [comment]
داش مرسی.داش یه سوال آخر
من کارم طراحی وب است.میخوام یه سایت برای sni اختصاصی برای خودم درست کنم که بجای یاهو برای ریلیتی بنویس.اگه اینکارو کنم اونوقت ترافیک از سایت sni هم مصرف میشه ؟ یا اینچیز فقط یه ادرس فیک است ؟؟

**Comment by ImanMontajabi** [comment]
> داش مرسی.داش یه سوال آخر من کارم طراحی وب است.میخوام یه سایت برای sni اختصاصی برای خودم درست کنم که بجای یاهو برای ریلیتی بنویس.اگه اینکارو کنم اونوقت ترافیک از سایت sni هم مصرف میشه ؟ یا اینچیز فقط یه ادرس فیک است ؟؟

قبلا اسکریپت گرفتن tls برای دامنه روی یه سایت وردپرسی رو انجام دادن دیده بودمش ولی مشکلش اینه که دامنه نباید به اسم خودت باشه و اگر لازم شد بتونی دائما عوضش کنی دامنه‌های ناشناس رو میزارن توی gray list فکر کنم یعنی روش اختلاله. ولی نه فقط certificate دامنه‌ی سایت رو جعل میکنه ترافیکی مصرف نمیشه

**Comment by ebiraaam** [comment]
مرسی داش فدات
