### ISSUE TITLE
خطا نصب

### ISSUE THREAD

**Issue by asna220** [ImanMontajabi/TLS-Checker#6]
سلام 
وقتی در کنسول اولین دستور را می زنیم
pip install -r requirements.txt
 این خطا را می دهد
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pip install -r requirements.txt
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ImanMontajabi** [comment]
> سلام وقتی در کنسول اولین دستور را می زنیم pip install -r requirements.txt این خطا را می دهد pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
> 
> * pip install -r requirements.txt
> * ```
>     + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

توی مسیری که فایل reqiurements.txt و فایل .py وجود داره این دستور رو بزن میتونی فقط دستور دوم رو بزنی و در جواب سوالی که میگه میخواهد پکیچ ها خودکار نصب بشوند y را بزن ولی دقت کن توی مسیر فایل ها باشی و اگر از مک یا لینوکس استفاده میکنی به جای pip از pip3 باید استفاده کنی

**Comment by asna220** [comment]
سلام 
 از یک فولدر هم اجرا کردم باز همان خطا را داد 
 دستور دوم را هم زدم 
 خطای زیر را داد.
 python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.       Check the spelling of the name, or if a path was included, verify that the path is correct and try again.               At line:1 char:1                                                                                                        + python tls-checker.py                                                                                                 + ~~~~~~                                                                                                                    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException                                  + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ImanMontajabi** [comment]
باید پایتون رو بزاری توی path اگه بلدی یا سرچ کن روشش رو یا از اول پایتون رو نصب کن و موقع نصب تیک path رو بزن

**Comment by ImanMontajabi** [comment]
> سلام ویندوز 10استفاده می کنم از یک فولدر هم اجرا کردم باز همان خطا را داد دستور دوم را هم زدم خطای زیر را داد. python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + python tls-checker.py + ~~~~~~ + CategoryInfo : ObjectNotFound: (python:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException

باید پایتون رو بزاری توی path اگه بلدی یا سرچ کن روشش رو یا از اول پایتون رو نصب کن و موقع نصب تیک path رو بزن

**Comment by asna220** [comment]
سلام مجدد 
تمام کارهایی که گفتید انجام داد
پیام خطا
PS C:\Python\Python311> pip install -r requirements.txt                                                                 pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the   spelling of the name, or if a path was included, verify that the path is correct and try again.                         At line:1 char:1                                                                                                        + pip install -r requirements.txt                                                                                       + ~~~                                                                                                                       + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException                                     + FullyQualifiedErrorId : CommandNotFoundException                                                                                                                                                                                          PS C:\Python\Python311> python tls-checker.py                                                                                                                                                                                                   ** Please install required modules: pip install -r requirements.txt **                                                  - Would you like to install requirements automatically? [y=YES, n=NO]:n                                                 PS C:\Python\Python311> python tls-checker.py                                                                                                                                                                                                   ** Please install required modules: pip install -r requirements.txt **                                                  - Would you like to install requirements automatically? [y=YES, n=NO]:y                                                 Traceback (most recent call last):                                                                                        File "C:\Python\Python311\tls-checker.py", line 10, in <module>                                                           import dns.resolver                                                                                                 ModuleNotFoundError: No module named 'dns'                                                                                                                                                                                                      During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):                                                                                        File "C:\Python\Python311\tls-checker.py", line 19, in <module>                                                           subprocess.run('pip3 install -r requirements.txt'.split(' '))                                                         File "C:\Python\Python311\Lib\subprocess.py", line 548, in run                                                            with Popen(*popenargs, **kwargs) as process:                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      File "C:\Python\Python311\Lib\subprocess.py", line 1024, in __init__                                                      self._execute_child(args, executable, preexec_fn, close_fds,                                                          File "C:\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child                                                hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                          FileNotFoundError: [WinError 2] The system cannot find the file specified                                               PS C:\Python\Python311>

**Comment by ImanMontajabi** [comment]
> سلام مجدد تمام کارهایی که گفتید انجام داد از مسیر زیر راهنمایی گرفتم در مسیر ویندوز قرار دادم https://novablog.ir/%D9%86%D8%B5%D8%A8-%D9%88-%D9%BE%DB%8C%DA%A9%D8%B1%D8%A8%D9%86%D8%AF%DB%8C-%D9%BE%D8%A7%DB%8C%D8%AA%D9%88%D9%86-%D8%AF%D8%B1-%D9%88%DB%8C%D9%86%D8%AF%D9%88%D8%B2/ پیام خطا PS C:\Python\Python311> pip install -r requirements.txt pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + pip install -r requirements.txt + ~~~ + CategoryInfo : ObjectNotFound: (pip:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException PS C:\Python\Python311> python tls-checker.py ** Please install required modules: pip install -r requirements.txt ** - Would you like to install requirements automatically? [y=YES, n=NO]:n PS C:\Python\Python311> python tls-checker.py ** Please install required modules: pip install -r requirements.txt ** - Would you like to install requirements automatically? [y=YES, n=NO]:y Traceback (most recent call last): File "C:\Python\Python311\tls-checker.py", line 10, in import dns.resolver ModuleNotFoundError: No module named 'dns' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Python\Python311\tls-checker.py", line 19, in subprocess.run('pip3 install -r requirements.txt'.split(' ')) File "C:\Python\Python311\Lib\subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python\Python311\Lib\subprocess.py", line 1024, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Python\Python311\Lib\subprocess.py", line 1509, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [WinError 2] The system cannot find the file specified PS C:\Python\Python311>

وقتی توی cmd تایپ میکنی python وارد محیط پایتون میشی؟

**Comment by asna220** [comment]
C:\Python\Python311>python                                                                                              Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32                        Type "help", "copyright", "credits" or "license" for more information.                                                  >>>

**Comment by asna220** [comment]
C:\TLS-Checker-1.1.0>pip                                                                                                'pip' is not recognized as an internal or external command,                                                             operable program or batch file.                                                                                                                                                                                                                 C:\TLS-Checker-1.1.0>

**Comment by ImanMontajabi** [comment]
> C:\TLS-Checker-1.1.0>pip 'pip' is not recognized as an internal or external command, operable program or batch file. C:\TLS-Checker-1.1.0>

- pip روی سیستمت یا نصب نشده که میتونی جداگونه از این لینک نصبش کنی:
https://pip.pypa.io/en/stable/installation/
- یا باید pip رو هم بزاری توی path ویندوزت که احتمالا مشکلت حل میشه:
بگرد pip رو پیدا شبیه به کاری که با پایتون کردی و آدرسش رو مثل همون آموزشه بزار توی path

**Comment by shahrokh451** [comment]
سلام تمام مراحل را طی  کردم در  CMD  وقتی دستور کشور را وارد میکنم ارور    ..........................؟۲۵         میده و برمیگرده سر دستور  tls checker

**Comment by shahrokh451** [comment]
![ERROR](https://github.com/ImanMontajabi/TLS-Checker/assets/52835737/4ed7ef3a-e94c-44b9-8d22-265f0f8b081d)

**Comment by shahrokh451** [comment]
![error 2](https://github.com/ImanMontajabi/TLS-Checker/assets/52835737/a866593b-a7cd-4f01-8fdf-41d4a557ec19)
