### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by nimaafallah** [ImanMontajabi/TLS-Checker#8]
سلام دمت گرم اقا 
یه مشکلی دارم میخوام ران کنم این پیغام میاد:
root@i9:~/TLS# python tls-checker.py
  File "tls-checker.py", line 45
    with open(f'./{file_name}.csv') as urls:
                                 ^
SyntaxError: invalid syntax

**Comment by ImanMontajabi** [comment]
> سلام دمت گرم اقا یه مشکلی دارم میخوام ران کنم این پیغام میاد: root@i9:~/TLS# python tls-checker.py File "tls-checker.py", line 45 with open(f'./{file_name}.csv') as urls: ^ SyntaxError: invalid syntax

سلام از رو پیغام معلومه داری روی لینوکس اجرا میکنی توی لینوکس دستور python3 اولش باید بزنی نه python

**Comment by nimaafallah** [comment]
بله دقیقا، مشکل حل شد این که گفتین رو زدم.
ممنون
