### ISSUE TITLE
اهمیت و تاثیر SNI

### ISSUE THREAD

**Issue by sajjad5221** [ImanMontajabi/TLS-Checker#9]
سلام وقت بخیر. ممنون بابت پروژه باحالت :)
یه سوال داشتم. به نظرت SNI چقدر در سرعت تاثیر داره؟ چیزی که من میشنوم اینه که SNI مهم نیست و تمیز بودن ip یا رنج اون اهمیت خیلی بیشتری داره. و اینکه چجوری SNI بهتری میتونیم پیدا کنیم. 
لطفا اگر امکان داره یه توضیح در موردش بده. ممنون

**Comment by ImanMontajabi** [comment]
> سلام وقت بخیر. ممنون بابت پروژه باحالت :) یه سوال داشتم. به نظرت SNI چقدر در سرعت تاثیر داره؟ چیزی که من میشنوم اینه که SNI مهم نیست و تمیز بودن ip یا رنج اون اهمیت خیلی بیشتری داره. و اینکه چجوری SNI بهتری میتونیم پیدا کنیم. لطفا اگر امکان داره یه توضیح در موردش بده. ممنون

سلام راستش نه تخصص من شبکه است و نه اطلاع دقیقی از عملکرد dpi چینی دارم، مثلا توی کانال رسمی Hiddify راجع به sni گفته شد که AS مهمه، اضافه کردمش :) توی اسکنر رسمی ریلیتی کشورها رو قرار داده بود منم گذاشتم توی نتیجه‌ سرچ، توی توییتر موضوع سایت های ایرانی مطرح شد(سگارو) اون ها رو هم قرار دادم. به نظر خودم اینا دوتا کار کردند یکی یه وایت لیست درست کردند فقط ترافیک sni های مجاز رو عبور بدهند، یکی آدرس sni رو resolve میکنند اگر با آی‌پی کانفیگت یکی نباشه اجازه‌ی عبور نمیده اینجوری برای بعضیا ریلیتی از کار افتاده این نظر منه ممکن اشتباه باشه

**Comment by Yasin-Dev81** [comment]
> سلام وقت بخیر. ممنون بابت پروژه باحالت :) یه سوال داشتم. به نظرت SNI چقدر در سرعت تاثیر داره؟ چیزی که من میشنوم اینه که SNI مهم نیست و تمیز بودن ip یا رنج اون اهمیت خیلی بیشتری داره. و اینکه چجوری SNI بهتری میتونیم پیدا کنیم. لطفا اگر امکان داره یه توضیح در موردش بده. ممنون

هردوش مهمه و از همه اینا مهمتر اینه که رنج آی‌پی سرور به رنج آی‌پی سرور sniی ما نزدیک باشه.
معمولا از سایت https://bgp.tools/ این مساله رو چک میکنن.
بعد از وارد کردن آی‌پی سرور از DNS > Show Forward DNS یه لیست از sniهایی رو بهت نشون میده که رنج آی‌پی سرورشون با رنج آی‌پی سرورت یکیه (البته باید دونه دونه چک کنی که فیلتر نباشن و TLS ورژن 1.3 هم باشن که کار وقت گیریه متاسفانه)
